name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve? What are you trying to do?
      placeholder: I'm trying to monitor tenant isolation but there's no tool for...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you'd like to happen
      placeholder: A new tool called `citus_tenant_monitor` that shows...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New tool
        - Improve existing tool
        - Advisor / recommendation
        - Configuration
        - Documentation
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or examples
